version: '3.9'

services:
  app:
    container_name: miapp
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: